[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run preview"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Nixpacks configuration for optimal build
[build.nixpacksConfig]
nodeVersion = "18"

[environments.production]
variables = {}

[environments.staging]
variables = {}