// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eicddzwfalnrttrmyppg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpY2RkendmYWxucnR0cm15cHBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNTM0MjYsImV4cCI6MjA3MDkyOTQyNn0.wM2scuHrjE5GXg3OJc4-YbZPCFmXXirheP_EQZ8_fZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});